/**
 * gen-skills.mjs — scans skills/<id>/SKILL.md and emits two generated files:
 *
 *   src/skills.generated.ts               host-side: PACKAGED_SKILLS with full bodies
 *   src/client/skill-catalog.generated.ts client-side: SKILL_CATALOG (id + description only)
 *
 * Run automatically by build.mjs and test/run.mjs before bundling.
 * Both outputs are gitignored — the skills/ tree is the source of truth.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const skillsDir = join(root, 'skills')

const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/

/** Parse `name:` / `description:` out of YAML frontmatter (flat scalars only). */
function parseFrontmatter(raw) {
  const out = {}
  for (const line of raw.split(/\r?\n/)) {
    const m = line.match(/^(name|description):\s*(.*)$/)
    if (!m) continue
    let value = m[2].trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    out[m[1]] = value
  }
  return out
}

const entries = []
const errors = []

for (const id of readdirSync(skillsDir).sort()) {
  const dir = join(skillsDir, id)
  if (!statSync(dir).isDirectory()) continue
  const file = join(dir, 'SKILL.md')
  let raw
  try {
    raw = readFileSync(file, 'utf8')
  } catch {
    errors.push(`${id}: missing SKILL.md`)
    continue
  }
  const fm = raw.match(FRONTMATTER)
  if (!fm) {
    errors.push(`${id}: no frontmatter block`)
    continue
  }
  const meta = parseFrontmatter(fm[1])
  const body = raw.slice(fm[0].length).trim()
  if (meta.name !== id) {
    errors.push(`${id}: frontmatter name is ${JSON.stringify(meta.name)}, expected ${JSON.stringify(id)}`)
    continue
  }
  if (!meta.description) {
    errors.push(`${id}: frontmatter missing description`)
    continue
  }
  if (!body.startsWith('# ')) {
    errors.push(`${id}: body must start with a "# Title" heading`)
    continue
  }
  entries.push({ id, description: meta.description, body })
}

if (errors.length) {
  for (const e of errors) console.error(`gen-skills: ${e}`)
  process.exit(1)
}

const hostOut = `// GENERATED by scripts/gen-skills.mjs — do not edit. Source: skills/<id>/SKILL.md
export interface PackagedSkill {
  id: string
  description: string
  body: string
}

export const PACKAGED_SKILLS: Record<string, PackagedSkill> = ${JSON.stringify(
  Object.fromEntries(entries.map((e) => [e.id, e])),
  null,
  2
)}
`

const clientOut = `// GENERATED by scripts/gen-skills.mjs — do not edit. Source: skills/<id>/SKILL.md
export interface CatalogSkill {
  id: string
  description: string
}

export const SKILL_CATALOG: CatalogSkill[] = ${JSON.stringify(
  entries.map((e) => ({ id: e.id, description: e.description })),
  null,
  2
)}
`

writeFileSync(join(root, 'src/skills.generated.ts'), hostOut)
writeFileSync(join(root, 'src/client/skill-catalog.generated.ts'), clientOut)
console.log(`gen-skills: embedded ${entries.length} skills`)
