/**
 * Advisor output quarantine, ported from oh-my-pi (MIT — see
 * NOTICE-oh-my-pi-LICENSE). An advisor turn that requests unavailable tools or
 * generates output-only destructive directives is replaced with a sanitized
 * error before anything becomes model-visible.
 */
import type { LlmContentBlock } from './types'

export const ADVISOR_QUARANTINE_PREFIX = 'Advisor response quarantined'

/** Signals that an advisor response was discarded before it could become model-visible context. */
export class AdvisorOutputQuarantinedError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'AdvisorOutputQuarantinedError'
  }
}

interface AdvisorOutputHazard {
  label: string
  pattern: RegExp
}

const ADVISOR_OUTPUT_ONLY_HAZARDS: readonly AdvisorOutputHazard[] = [
  { label: 'account-deletion claim', pattern: /\buser\b.{0,80}\b(?:deleted|erased)\b.{0,80}\baccount\b/i },
  {
    label: 'instruction override',
    pattern: /\bignore\s+(?:all\s+)?(?:prior|previous|earlier)\s+(?:user\s+)?instructions\b/i
  },
  {
    label: 'destructive shell command',
    pattern: /\brm\s+(?=(?:-[a-z]+\s*)*-[a-z]*r[a-z]*)(?=(?:-[a-z]+\s*)*-[a-z]*f[a-z]*)(?:-[a-z]+\s*)+/i
  },
  { label: 'denial instruction', pattern: /\bdeny\s+(?:this|it|the\s+request)\s+if\s+(?:asked|questioned)\b/i }
]

/**
 * Consecutive quarantined advisor turns tolerated before the failure is
 * surfaced. One silent re-prime may recover a one-off hallucination; a
 * persistent quarantine loop is a real supervision gap. Reset on success.
 */
export const MAX_QUARANTINE_RETRIES = 2

/**
 * Check one advisor assistant turn (its content blocks) against the grant and
 * the hazard list.
 *
 * @param blocks - the assistant turn's content blocks.
 * @param availableToolNames - tools granted to this advisor.
 * @param sourceText - provenance text (current delta + tool results seen by
 *   the advisor); hazards already present there were not generated by the
 *   advisor and do not quarantine on their own.
 * @returns the quarantine message when the turn must be replaced, else undefined.
 */
export function quarantineAdvisorUnsafeOutput(
  blocks: readonly LlmContentBlock[],
  availableToolNames: ReadonlySet<string>,
  sourceText = ''
): string | undefined {
  const reasons: string[] = []
  const unavailableToolNames = new Set<string>()
  const generatedParts: string[] = []

  for (const block of blocks) {
    if (block.type === 'tool-call' && !availableToolNames.has(block.name)) {
      unavailableToolNames.add(block.name)
    }
    if (block.type === 'tool-call' && block.name === 'advise') {
      try {
        const args = JSON.parse(block.arguments) as { note?: unknown }
        if (typeof args.note === 'string') generatedParts.push(args.note)
      } catch {
        /* unparseable arguments are not generated text */
      }
    }
    if (block.type === 'text') generatedParts.push(block.text)
  }

  if (unavailableToolNames.size > 0) {
    const names = [...unavailableToolNames].sort()
    const toolLabel = names.length === 1 ? 'tool' : 'tools'
    reasons.push(`requested unavailable ${toolLabel} ${names.join(', ')}`)
  }

  const generatedText = generatedParts.join('\n')
  if (generatedText) {
    const labels: string[] = []
    const matchedLabels: string[] = []
    for (const hazard of ADVISOR_OUTPUT_ONLY_HAZARDS) {
      if (!hazard.pattern.test(generatedText)) continue
      matchedLabels.push(hazard.label)
      if (!hazard.pattern.test(sourceText)) labels.push(hazard.label)
    }
    // A transcript can quote a destructive command while the advisor turns it
    // into a new instruction; the output-only override remains sufficient
    // provenance to quarantine that combination.
    if (
      matchedLabels.includes('destructive shell command') &&
      labels.includes('instruction override') &&
      !labels.includes('destructive shell command')
    ) {
      labels.push('destructive shell command')
    }
    if (labels.includes('destructive shell command') || labels.length >= 3) {
      reasons.push(`generated output-only destructive directives: ${labels.join(', ')}`)
    }
  }

  if (reasons.length === 0) return undefined
  return `${ADVISOR_QUARANTINE_PREFIX}: ${reasons.join('; ')}`
}

/**
 * Build the provenance text used to decide whether hazardous output was
 * generated by the advisor or came from model-visible primary/tool context:
 * the current delta plus every tool-result text the advisor has seen.
 */
export function buildAdvisorQuarantineSourceText(
  currentInput: string,
  toolResultTexts: readonly string[]
): string {
  const parts: string[] = []
  if (currentInput) parts.push(currentInput)
  parts.push(...toolResultTexts)
  return parts.join('\n')
}
